services:
  postgres:
    image: postgres:15
    container_name: cloud_task_postgres
    environment:
      POSTGRES_DB: cloud_tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloud_tasks"]
      interval: 10s
      timeout: 5s
      retries: 10

  api-service:
    build:
      context: ./api-service
    container_name: api-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/cloud_tasks
      DB_USERNAME: postgres
      DB_PASSWORD: 123
      AWS_REGION: eu-north-1
      AWS_SQS_QUEUE_URL: https://sqs.eu-north-1.amazonaws.com/498713386924/worker_queue
      AWS_S3_BUCKET_NAME: ram-cloud-task-bucket-123
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8080:8080"

  worker-service:
    build:
      context: ./worker-service
    container_name: worker-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/cloud_tasks
      DB_USERNAME: postgres
      DB_PASSWORD: 123
      AWS_REGION: eu-north-1
      AWS_SQS_QUEUE_URL: https://sqs.eu-north-1.amazonaws.com/498713386924/worker_queue
      AWS_S3_BUCKET_NAME: ram-cloud-task-bucket-123
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8081:8081"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - api-service
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  postgres_data: